"""Settings → Keyboard & shortcuts and Mouse & touchpad, as niri config.

binds.kdl: the installer's catalogue (binds.json: every bind with its KDL)
with the keys changed in Settings, the turned-off ones left out, and your own
binds after them. niri rejects a key bound twice in one binds block, so no
key is ever written twice: a changed bind takes its keys from whichever bind
held them, an own bind from a vitrum one, a later own bind from an earlier.

input.kdl: the mouse and touchpad sections. niri does not merge pointer
sections across includes, so these replace config.kdl's, and an overrides.kdl
mouse { } replaces these.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


def load_catalogue(path: Path):
    """The catalogue, or None when it is missing, empty, or from before the `kdl`
    field (writing binds.kdl from it would leave niri with no binds at all)."""
    try:
        cat = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if not isinstance(cat, list) or not cat:
        return None
    for b in cat:
        if isinstance(b, dict) and b.get("hidden"):
            continue
        if not (isinstance(b, dict) and isinstance(b.get("keys"), str) and b["keys"]
                and isinstance(b.get("kdl"), str) and b["kdl"]):
            return None
    return cat


_PART = re.compile(r"^[A-Za-z0-9_\-]+$")
_MODS = {"mod": "Mod", "super": "Super", "win": "Super", "logo": "Super", "meta": "Super",
         "ctrl": "Ctrl", "control": "Ctrl", "alt": "Alt", "shift": "Shift",
         "iso_level3_shift": "ISO_Level3_Shift", "iso_level5_shift": "ISO_Level5_Shift"}
_ORDER = ["Mod", "Super", "Ctrl", "Alt", "Shift", "ISO_Level3_Shift", "ISO_Level5_Shift"]


def canonical_keys(s) -> str | None:
    """niri's spelling of a key combo (modifiers in a fixed order, aliases folded), or None if niri can't parse it."""
    if not isinstance(s, str):
        return None
    parts = s.strip().split("+")
    if not all(_PART.match(p) for p in parts):
        return None
    mods = set()
    for m in parts[:-1]:
        c = _MODS.get(m.lower())
        if c is None or c in mods:
            return None
        mods.add(c)
    return "+".join([m for m in _ORDER if m in mods] + [parts[-1]])


def _q(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def binds_kdl(catalogue: list, settings: dict) -> str:
    kb = (settings.get("keybinds") or {}) if isinstance(settings, dict) else {}
    changes = kb.get("changes") if isinstance(kb.get("changes"), dict) else {}
    own = kb.get("own") if isinstance(kb.get("own"), list) else []
    rows = []  # [keys, kdl, priority]: 0 vitrum, 1 changed vitrum, 2+ own (later wins)
    for b in catalogue:
        if not isinstance(b, dict) or not b.get("keys") or not b.get("kdl"):
            continue
        keys = b["keys"]
        if keys in changes and not changes[keys]:
            continue
        new = canonical_keys(changes.get(keys)) if keys in changes else None
        rows.append([new, b["kdl"], 1] if new else [canonical_keys(keys) or keys, b["kdl"], 0])
    for i, o in enumerate(own):
        if not isinstance(o, dict) or not canonical_keys(o.get("keys")) or not str(o.get("command") or "").strip():
            continue
        title = str(o.get("title") or o["command"])
        rows.append([canonical_keys(o["keys"]), f"hotkey-overlay-title={_q(title)} {{ spawn-sh {_q(o['command'])}; }}", 2 + i])
    best = {}
    for r in rows:
        k = r[0].lower()
        if k not in best or r[2] >= best[k][2]:
            best[k] = r
    keep = {id(r) for r in best.values()}
    lines = [f"    {r[0]} {r[1]}" for r in rows if id(r) in keep]
    return ("// Generated by vitrum-theme from binds.json (KEYBINDS.md) and Settings → Keyboard & shortcuts.\n"
            "// Do not edit: change keys in Settings, or add binds to overrides.kdl.\n"
            "binds {\n" + "\n".join(lines) + "\n}\n")


def _num(v, default: float, lo: float, hi: float) -> float:
    try:
        x = float(v)
    except (TypeError, ValueError):
        x = default
    return max(lo, min(hi, x))


def input_kdl(settings: dict) -> str:
    inp = (settings.get("input") or {}) if isinstance(settings, dict) else {}
    m = inp.get("mouse") if isinstance(inp.get("mouse"), dict) else {}
    t = inp.get("touchpad") if isinstance(inp.get("touchpad"), dict) else {}
    mouse = [f'accel-profile "{"adaptive" if m.get("accel") else "flat"}"',
             f"accel-speed {_num(m.get('speed'), 0.0, -1, 1):.2f}",
             f"scroll-factor {_num(m.get('scroll'), 1.0, 0.1, 5):.2f}"]
    if m.get("natural"):
        mouse.append("natural-scroll")
    pad = (["tap"] if t.get("tap", True) else []) + ["dwt"] + (["natural-scroll"] if t.get("natural", True) else []) + [
        'accel-profile "adaptive"', f"accel-speed {_num(t.get('speed'), 0.25, -1, 1):.2f}",
        'scroll-method "two-finger"', 'click-method "clickfinger"']
    body = lambda xs: "".join(f"        {x}\n" for x in xs)
    return ("// Generated by vitrum-theme from Settings → Mouse & touchpad. Do not edit.\n"
            "input {\n    mouse {\n" + body(mouse) + "    }\n    touchpad {\n" + body(pad) + "    }\n}\n")
